import { Game } from "../Game";

import { Direction } from "../Libraries/Direction";
import { Random } from "../Libraries/Random";

import { BlueTektite } from "../Enemies/BlueTektite";
import { Tektite } from "../Enemies/Tektite";
import { BlueMoblin } from "../Enemies/BlueMoblin";
import { Moblin } from "../Enemies/Moblin";
import { BlueOctorok } from "../Enemies/BlueOctorok";
import { Octorok } from "../Enemies/Octorok";

import { HeartReceptacle } from "../Items/HeartReceptacle";
import { Sword as SwordItem } from "../Items/Sword";
import { Passage } from "./Passage";
import { Scene } from "./Scene";
import { World } from "./World";

export class Map {
  Game: Game;

  worlds: World[];

  spawnWorldIndex: number;
  spawnSceneColl: number;
  spawnSceneRow: number;
  spawnCellColl: number;
  spawnCellRow: number;

  constructor(game: Game) {
    this.Game = game;

    this.spawnWorldIndex = 0;

    this.spawnSceneColl = 1;
    this.spawnSceneRow = 2;

    this.spawnCellColl = 7;
    this.spawnCellRow = 5.5;

    this.worlds = [];

    this.worlds[0] = new World({
      game: this.Game,
      nbCol: 3,
      nbRow: 3,
      defaultMusic: this.Game.AssetManager.getSound("./sounds/music/overworld.mp3", true),
      defaultBrick: this.Game.BrickCollection.get("default"),
      defaultBackgroundColor: "#ffd4aa"
    });

    this.worlds[0].scenes[0][0].loadBricks([
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ],
      [
        "white-wall",
        "white-wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "white-wall",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "default"
      ],
      [
        "white-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "white-wall",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "default"
      ],
      [
        "white-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "white-wall",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "default",
        "default",
        "default",
        "grave",
        "default",
        "default",
        "default"
      ],
      [
        "white-wall",
        "white-wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "stairs",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "stairs",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ]
    ]);

    this.worlds[0].scenes[0][0].backgroundColor = "#747474";

    this.worlds[0].scenes[0][0].music = this.Game.AssetManager.getSound(
      "./sounds/music/death_mountain.mp3",
      true
    );

    this.worlds[0].scenes[0][0].enemies = [
      new BlueOctorok({
        game: this.Game,
        x: 2 * 64,
        y: 2 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Down
      }),
      new BlueOctorok({
        game: this.Game,
        x: 5 * 64,
        y: 5 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new BlueOctorok({
        game: this.Game,
        x: 13 * 64,
        y: 3 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      })
    ];

    this.worlds[0].scenes[1][0].loadBricks([
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "default",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "default"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "default",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "default"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "default",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "default"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ]
    ]);

    this.worlds[0].scenes[1][0].backgroundColor = "#747474";

    this.worlds[0].scenes[1][0].music = this.Game.AssetManager.getSound(
      "./sounds/music/death_mountain.mp3",
      true
    );

    this.worlds[0].scenes[1][0].enemies = [
      new BlueMoblin({
        game: this.Game,
        x: 5 * 64,
        y: 8 * 64,
        speed: 4,
        direction: Direction.Up
      }),
      new BlueMoblin({
        game: this.Game,
        x: 8 * 64,
        y: 4 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Left
      }),
      new BlueMoblin({
        game: this.Game,
        x: 10 * 64,
        y: 2 * 64,
        speed: 4,
        direction: Direction.Down
      })
    ];

    this.worlds[0].scenes[2][0].loadBricks([
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "passage",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "white-wall-bl",
        "white-wall",
        "white-wall"
      ],
      [
        "default",
        "default",
        "default",
        "monument-tl",
        "monument-tr",
        "default",
        "default",
        "white-tree",
        "default",
        "default",
        "monument-tl",
        "monument-tr",
        "default",
        "default",
        "white-wall",
        "white-wall"
      ],
      [
        "default",
        "default",
        "default",
        "monument-bl",
        "monument-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "monument-bl",
        "monument-br",
        "default",
        "default",
        "white-wall",
        "white-wall"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "white-wall",
        "white-wall"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "grave",
        "default",
        "grave",
        "default",
        "default",
        "default",
        "default",
        "default",
        "white-wall",
        "white-wall"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "white-wall",
        "white-wall"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "white-wall-tl",
        "white-wall",
        "white-wall"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall-t",
        "white-wall",
        "white-wall",
        "white-wall"
      ],
      [
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall",
        "white-wall"
      ]
    ]);

    this.worlds[0].scenes[2][0].backgroundColor = "#747474";

    this.worlds[0].scenes[2][0].music = this.Game.AssetManager.getSound(
      "./sounds/music/death_mountain.mp3",
      true
    );

    this.worlds[0].scenes[2][0].passages = [
      new Passage({
        game: this.Game,
        scene: this.worlds[0].scenes[2][0],
        c: 7,
        r: 1,
        targetWorldIndex: 2,
        targetSceneC: 1,
        targetSceneR: 1
      })
    ];

    this.worlds[0].scenes[2][0].enemies = [
      new BlueOctorok({
        game: this.Game,
        x: 5 * 64,
        y: 4 * 64,
        speed: 4,
        direction: Direction.Down
      }),
      new BlueOctorok({
        game: this.Game,
        x: 9 * 64,
        y: 6 * 64,
        speed: 4,
        direction: Direction.Right
      }),
      new BlueOctorok({
        game: this.Game,
        x: 12 * 64,
        y: 3 * 64,
        speed: 4,
        direction: Direction.Down
      }),
      new BlueTektite({
        game: this.Game,
        x: 7 * 64,
        y: 7 * 64
      })
    ];

    this.worlds[0].scenes[0][1].loadBricks([
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "stairs",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "stairs",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-bl",
        "wall"
      ],
      [
        "wall",
        "default",
        "default",
        "single-red-wall",
        "single-red-wall",
        "single-red-wall",
        "single-red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-bl"
      ],
      [
        "wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-red-wall",
        "single-red-wall",
        "single-red-wall",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "wall",
        "default",
        "default",
        "single-red-wall",
        "single-red-wall",
        "single-red-wall",
        "single-red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-red-wall",
        "single-red-wall",
        "single-red-wall",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "wall",
        "default",
        "default",
        "single-red-wall",
        "single-red-wall",
        "single-red-wall",
        "single-red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-tl"
      ],
      [
        "wall",
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-tl",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-tr",
        "default",
        "default",
        "wall-tl",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "default",
        "default",
        "wall",
        "wall",
        "wall"
      ]
    ]);
    this.worlds[0].scenes[0][1].enemies = [
      new Octorok({
        game: this.Game,
        x: 6 * 64,
        y: 4 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Left
      }),
      new Octorok({
        game: this.Game,
        x: 4 * 64,
        y: 6 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Left
      }),
      new Octorok({
        game: this.Game,
        x: 7 * 64,
        y: 2 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new Octorok({
        game: this.Game,
        x: 13 * 64,
        y: 2 * 64,
        speed: 3,
        direction: Direction.Down
      })
    ];

    this.worlds[0].scenes[1][1].loadBricks([
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-bl",
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "wall-bl",
        "wall"
      ],
      [
        "wall-br",
        "default",
        "default",
        "single-wall",
        "default",
        "single-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "wall-bl"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "single-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "default"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "wall-tr",
        "default",
        "default",
        "single-wall",
        "default",
        "single-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "wall-tl"
      ],
      [
        "wall",
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-tl",
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "wall-tl",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "default",
        "default",
        "wall",
        "wall",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "default",
        "default",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ]
    ]);
    this.worlds[0].scenes[1][1].enemies = [
      new Octorok({
        game: this.Game,
        x: 4 * 64,
        y: 5 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new Octorok({
        game: this.Game,
        x: 10 * 64,
        y: 3 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new Octorok({
        game: this.Game,
        x: 13 * 64,
        y: 7 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new Octorok({
        game: this.Game,
        x: 12 * 64,
        y: 6 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Left
      }),
    ];

    this.worlds[0].scenes[2][1].loadBricks([
      [
        "wall",
        "wall",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree"
      ],
      [
        "wall",
        "wall",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree"
      ],
      [
        "wall",
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree"
      ],
      [
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree",
        "default",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "default",
        "default",
        "tree",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "tree",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "default",
        "default",
        "tree",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree"
      ],
      [
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree",
        "default",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "wall",
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree"
      ],
      [
        "wall",
        "wall",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "wall",
        "wall",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ]
    ]);
    this.worlds[0].scenes[2][1].enemies = [
      new Octorok({
        game: this.Game,
        x: 3 * 64,
        y: 4 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Left
      }),
      new Octorok({
        game: this.Game,
        x: 5 * 64,
        y: 6 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Left
      }),
      new Octorok({
        game: this.Game,
        x: 10 * 64,
        y: 5 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new Octorok({
        game: this.Game,
        x: 14 * 64,
        y: 2 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Left : Direction.Down
      }),
    ];

    this.worlds[0].scenes[0][2].loadBricks([
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "default",
        "default",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall-br",
        "default",
        "default",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-bl",
        "wall",
        "wall"
      ],
      [
        "wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "default",
        "default",
        "wall-bl",
        "wall"
      ],
      [
        "wall",
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "default",
        "default",
        "wall-tl",
        "wall-t"
      ],
      [
        "wall",
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "single-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-tl",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ]
    ]);
    this.worlds[0].scenes[0][2].enemies = [
      new Tektite({
        game: this.Game,
        x: 3 * 64,
        y: 4 * 64
      }),
      new Tektite({
        game: this.Game,
        x: 5 * 64,
        y: 7 * 64
      }),
      new Tektite({
        game: this.Game,
        x: 10 * 64,
        y: 5 * 64
      })
    ];

    // Spawn scene
    this.worlds[0].scenes[1][2].loadBricks([
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "default",
        "default",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "passage",
        "wall",
        "wall-br",
        "default",
        "default",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-bl",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-bl",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default"
      ],
      [
        "wall-t",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-tl",
        "wall-t"
      ],
      [
        "wall",
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "wall-tl",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall-t",
        "wall",
        "wall",
        "wall"
      ],
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall"
      ]
    ]);

    this.worlds[0].scenes[1][2].passages = [
      new Passage({
        game: this.Game,
        scene: this.worlds[0].scenes[1][2],
        c: 3,
        r: 1,
        targetWorldIndex: 1,
        targetSceneC: 0,
        targetSceneR: 0
      })
    ];

    this.worlds[0].scenes[2][2].loadBricks([
      [
        "wall",
        "wall",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "wall",
        "wall",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "wall",
        "wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree"
      ],
      [
        "wall",
        "wall-br",
        "default",
        "default",
        "default",
        "default",
        "tree",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "wall-br",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree"
      ],
      [
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "wall-t",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree"
      ],
      [
        "wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree",
        "default",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree",
        "default",
        "tree"
      ],
      [
        "wall",
        "wall-tr",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tree"
      ],
      [
        "wall",
        "wall",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree"
      ],
      [
        "wall",
        "wall",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree",
        "tree"
      ]
    ]);
    this.worlds[0].scenes[2][2].enemies = [
      new Moblin({
        game: this.Game,
        x: 3 * 64,
        y: 5 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new Moblin({
        game: this.Game,
        x: 5 * 64,
        y: 7 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new Moblin({
        game: this.Game,
        x: 10 * 64,
        y: 5 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new Moblin({
        game: this.Game,
        x: 12 * 64,
        y: 7 * 64,
        speed: 3,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      })
    ];

    this.worlds[1] = new World({
      game: this.Game,
      nbCol: 1,
      nbRow: 1,
      defaultMusic: this.Game.AssetManager.getSound("./sounds/music/death_mountain.mp3", true),
      defaultBrick: this.Game.BrickCollection.get("default"),
      defaultBackgroundColor: "#0f0e0b"
    });

    this.worlds[1].scenes[0][0].loadBricks([
      [
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "fire",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "fire",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "red-wall"
      ],
      [
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "default",
        "default",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall",
        "red-wall"
      ]
    ]);

    this.worlds[1].scenes[0][0].permanentItems = [
      new SwordItem({
        game: this.Game,
        x: 8 * 64 - 14,
        y: 5 * 64
      })
    ];

    this.worlds[1].scenes[0][0].bottomEdgeCollision = function () {
      this.Game.Viewport.changeWorld(false, 0, 1, 2, 3, 1);
    };

    this.worlds[2] = new World({
      game: this.Game,
      nbCol: 2,
      nbRow: 2,
      defaultMusic: this.Game.AssetManager.getSound("./sounds/music/dungeon.mp3", true),
      defaultBrick: this.Game.BrickCollection.get("default-dungeon"),
      defaultBackgroundColor: "#078382"
    });

    this.worlds[2].scenes[0][0].loadBricks([
      [
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon"
      ]
    ]);

    this.worlds[2].scenes[0][0].enemies = [
      new BlueOctorok({
        game: this.Game,
        x: 2 * 64,
        y: 2 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Down
      }),
      new BlueOctorok({
        game: this.Game,
        x: 5 * 64,
        y: 5 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new BlueOctorok({
        game: this.Game,
        x: 13 * 64,
        y: 3 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new BlueOctorok({
        game: this.Game,
        x: 8 * 64,
        y: 6 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      })
    ];

    this.worlds[2].scenes[1][0].loadBricks([
      [
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon"
      ]
    ]);

    this.worlds[2].scenes[1][0].permanentItems = [
      new HeartReceptacle({
        game: this.Game,
        x: 8 * 64 - 13,
        y: 5 * 64
      })
    ];

    this.worlds[2].scenes[0][1].loadBricks([
      [
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon"
      ]
    ]);

    this.worlds[2].scenes[0][1].enemies = [
      new BlueTektite({
        game: this.Game,
        x: 2 * 64,
        y: 2 * 64
      }),
      new BlueTektite({
        game: this.Game,
        x: 5 * 64,
        y: 5 * 64
      }),
      new BlueTektite({
        game: this.Game,
        x: 13 * 64,
        y: 3 * 64
      }),
      new BlueTektite({
        game: this.Game,
        x: 8 * 64,
        y: 6 * 64
      })
    ];

    this.worlds[2].scenes[1][1].loadBricks([
      [
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon"
      ],
      [
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "default-dungeon",
        "default-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon",
        "wall-dungeon"
      ]
    ]);

    this.worlds[2].scenes[1][1].bottomEdgeCollision = function () {
      this.Game.Viewport.changeWorld(false, 0, 2, 0, 7, 1);
    };

    this.worlds[2].scenes[1][1].enemies = [
      new BlueMoblin({
        game: this.Game,
        x: 2 * 64,
        y: 2 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Right : Direction.Down
      }),
      new BlueMoblin({
        game: this.Game,
        x: 5 * 64,
        y: 5 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      }),
      new BlueMoblin({
        game: this.Game,
        x: 13 * 64,
        y: 3 * 64,
        speed: 4,
        direction: Random.getOneInt(2) ? Direction.Up : Direction.Down
      })
    ];
  }

  getSpawnWorld(): World {
    return this.worlds[this.spawnWorldIndex];
  }

  getSpawnScene(): Scene {
    return this.worlds[this.spawnWorldIndex].scenes[this.spawnSceneColl][
      this.spawnSceneRow
    ];
  }

  loopWorlds(callback: Function): void {
    this.worlds.forEach((world) => {
      callback(world);
    });
  }
}
